
name: Publish image

on:
  push:
    paths:
      - '.homebridge/**'
      - '.github/workflows/publish-docker.yml'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: docker.io/${{ secrets.DOCKER_REPO }}:latest
          push: true

